name: build-docker-image

on:
  workflow_dispatch:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker imaage
      run: docker build . --file Dockerfile --tag kawachou55/scraper:v0.0.2

    - run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - run: docker push kawachou55/scraper:v0.0.2

    - name: fetch data
      run: curl https://www.city.setagaya.lg.jp/mokuji/kusei/001/001/004/d00185364.html > docs/data.html
