name: build-docker-image

on:
  push:
    paths:
    - 'package*.json'
    - '*.js'
  workflow_dispatch:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
        registry: docker.io
        repository: kawachou55/html2csv
        tag: v0.0.3