name: main

on:
  schedule:
    - cron: '50 * * * *'
  workflow_dispatch:
    branches: [ feature/cron-and-build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: curl https://www.city.setagaya.lg.jp/mokuji/kusei/001/001/004/d00185364.html > docs/data.html
    - run: npm run build
    - run: git config --local user.email "kawachou@gmail.com"
    - run: git config --local user.name "kawachou"
    - run: git add docs
    - run: git commit -m "Update data.html and data.csv"

    - uses: ad-m/github-push-action@v0.6.0
      if: ${{ success() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
